Repository SkyAPM/go2sky, pull requests merged in 2019-12, with the labels that each got.

#37 Module name modification & Change license header
  .circleci/config.yml
  .github/CONTRIBUTING.md
  Makefile
  README.md
  doc.go
  example_trace_test.go
  go.mod
  golangci.yml
  internal/idgen/idgen.go
  internal/tool/error.go
  internal/tool/time.go
  noop.go
  noop_test.go
  plugins/gin/doc.go
  plugins/gin/example_gin_test.go
  plugins/gin/gin.go
  plugins/http/client.go
  plugins/http/doc.go
  plugins/http/example_http_test.go
  plugins/http/server.go
  propagation/propagation.go
  reporter/doc.go
  reporter/grpc.go
  reporter/grpc/common/CLR.proto
  reporter/grpc/common/JVM.proto
  reporter/grpc/common/common.proto
  reporter/grpc/common/trace-common.proto
  reporter/grpc/language-agent-v2/CLRMetric.pb.go
  reporter/grpc/language-agent-v2/CLRMetric.proto
  reporter/grpc/language-agent-v2/JVMMetric.pb.go
  reporter/grpc/language-agent-v2/JVMMetric.proto
  reporter/grpc/language-agent-v2/mock_trace/trace.mock.go
  reporter/grpc/language-agent-v2/trace.pb.go
  reporter/grpc/language-agent-v2/trace.proto
  reporter/grpc/register/InstancePing.pb.go
  reporter/grpc/register/InstancePing.proto
  reporter/grpc/register/Register.pb.go
  reporter/grpc/register/Register.proto
  reporter/grpc/register/mock_register/InstancePing.mock.go
  reporter/grpc/register/mock_register/Register.mock.go
  reporter/grpc_test.go
  reporter/log.go
  segment.go
  segment_test.go
  span.go
  span_opts.go
  span_test.go
  trace.go
  trace_opts.go
  trace_propagation_test.go
  trace_test.go
Labels: enhancement

#39 Fix example-gin
  plugins/gin/example_gin_test.go
Labels: bug

#38 http plugin lost status code
  plugins/http/server.go
Labels: bug

#40 Update README.md
  README.md
Labels: document

#41 Add TraceID(ctx context.Context)
  README.md
  segment.go
  trace.go
  trace_test.go
Labels: enhancement
