Repository SkyAPM/go2sky, pull requests merged in 2020-06, with the labels that each got.

#60 add 'Authentication' for grpc request
  reporter/grpc.go
  reporter/grpc_test.go
Labels: enhancement

#61 cannot customize the configuration the send span chan length
  reporter/grpc.go
  reporter/grpc_test.go
Labels: enhancement

#62 Support TLS with gRPCReporter
  Makefile
  README.md
  docs/GRPC-Reporter-Option.md
  reporter/grpc.go
  reporter/grpc_test.go
  test/test-data/certs/README.md
  test/test-data/certs/cert.crt
  test/test-data/certs/cert.key
Labels: enhancement

#63 Add missing documentation
  README.md
  docs/GRPC-Reporter-Option.md
Labels: document

#65 Add plugin to support teambition/gear framework
  README.md
  go.mod
  go.sum
  plugins/gear/doc.go
  plugins/gear/example_gear_test.go
  plugins/gear/gear.go
  plugins/gin/gin.go
  plugins/http/server.go
  span.go
Labels: plugin
