Repository SkyAPM/go2sky, pull requests merged in 2020-03, with the labels that each got.

#44 fix entryEndpointId & parentEndpointId bug
  noop.go
  propagation/propagation.go
  reporter/grpc.go
  segment.go
  span.go
  trace.go
Labels: bug

#45 Use github action
  .circleci/config.yml
  .github/workflows/ci.yaml
  Makefile
  README.md
  golangci.yml
  trace.go
Labels: enhancement

#46 update Register.proto and grpc version.
  go.mod
  reporter/grpc/common/CLR.pb.go
  reporter/grpc/common/JVM.pb.go
  reporter/grpc/common/common.pb.go
  reporter/grpc/common/trace-common.pb.go
  reporter/grpc/language-agent-v2/CLRMetric.pb.go
  reporter/grpc/language-agent-v2/JVMMetric.pb.go
  reporter/grpc/language-agent-v2/trace.pb.go
  reporter/grpc/register/InstancePing.pb.go
  reporter/grpc/register/Register.pb.go
  reporter/grpc/register/Register.proto
  reporter/grpc/register/mock_register/Register.mock.go
Labels: enhancement

#50 Recover the panic caused by close sendCh
  reporter/grpc.go
  reporter/grpc_test.go
Labels: enhancement

#52 Fix gin plugin bug
  plugins/gin/gin.go
Labels: bug, plugin
